apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api-unique
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - name: data-api
          image: {{ .Values.dataApi.image }}
          ports:
            - containerPort: {{ .Values.dataApi.port }}

