apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-unique
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backendApi.port }}

