apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-job
  namespace: health-namespace
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: health-check-script:v1
            command: ["/bin/bash", "-c", "./health-check-script.sh"]
            volumeMounts:
            - name: log-volume
              mountPath: /var/log
          restartPolicy: OnFailure
          volumes:
          - name: log-volume
            persistentVolumeClaim:
              claimName: health-check-pvc

