apiVersion: v1
kind: PersistentVolume
metadata:
  name: health-check-pv
spec:
  capacity:
    storage: 1Gi  # Adjust based on your needs
  accessModes:
    - ReadWriteOnce
  hostPath:  # Use hostPath for testing, switch to a cloud provider storage in production
    path: /var/log/health-check-logs  # Adjust the path as needed

