- name: Deploy Data API to Kind Cluster
  hosts: localhost
  tasks:
    - name: Install Helm community.kubernetes collection (if not already installed)
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.kubernetes
      register: helm_installed
      changed_when: helm_installed.rc != 0

    - name: Ensure Helm repository is added
      community.kubernetes.helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable

    - name: Deploy Data API with Helm
      community.kubernetes.helm:
        name: "{{ release_data }}"
        chart_ref: "../helm-data"  # Path to your Helm chart for Data API
        namespace: "{{ namespace_data }}"
        create_namespace: true
        state: present

